# Generated by Django 6.0.5 on 2026-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_totp_backup_codes_user_totp_enabled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='google_subject',
            field=models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=255, null=True, unique=True),
        ),
    ]
